spring:
  application:
    name: modulith.cqrs
  datasource:
    command:
      jdbc-url: jdbc:h2:mem:commanddb
      username: sa
      password:
      driver-class-name: org.h2.Driver
    query:
      jdbc-url: jdbc:h2:mem:querydb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  modulith:
    events:
      completion-mode: archive
      republish-outstanding-events-on-restart: true
  docker:
    compose:
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration
logging:
  level:
    gae.piaz.modulith.cqrs: DEBUG
    org.springframework.modulith: DEBUG
