@startuml
set separator none
title CQRSApplication

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("CQRSApplication.CQRSApplication_boundary", "CQRSApplication", $tags="") {
  Component(CQRSApplication.CQRSApplication.Command, "Command", $techn="Module", $descr="", $tags="", $link="")
  Component(CQRSApplication.CQRSApplication.Query, "Query", $techn="Module", $descr="", $tags="", $link="")
}

Rel(CQRSApplication.CQRSApplication.Query, CQRSApplication.CQRSApplication.Command, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml