@startuml
set separator none
title Query

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("Application.Application_boundary", "Application", $tags="") {
  Component(Application.Application.Command, "Command", $techn="Module", $descr="", $tags="", $link="")
  Component(Application.Application.Query, "Query", $techn="Module", $descr="", $tags="", $link="")
}

Rel(Application.Application.Query, Application.Application.Command, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml